# Generated by Django 5.2.1 on 2025-05-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Football',
            fields=[
                ('playername', models.CharField(primary_key=True, serialize=False)),
                ('age', models.IntegerField(max_length=50)),
                ('nationality', models.CharField()),
                ('club', models.CharField()),
                ('position', models.CharField()),
            ],
        ),
    ]
